# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_k_fold_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(559, 387)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(150, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.numFolds = QtWidgets.QComboBox(self.frame)
        self.numFolds.setObjectName("numFolds")
        self.numFolds.addItem("")
        self.numFolds.addItem("")
        self.numFolds.addItem("")
        self.numFolds.addItem("")
        self.numFolds.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.numFolds)
        self.groupBoxValorPositivo = QtWidgets.QGroupBox(self.frame)
        self.groupBoxValorPositivo.setObjectName("groupBoxValorPositivo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxValorPositivo)
        self.verticalLayout_2.setContentsMargins(2, 9, 2, 9)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBoxValorPositivo)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.comboBoxValorPositivo = QtWidgets.QComboBox(self.groupBoxValorPositivo)
        self.comboBoxValorPositivo.setObjectName("comboBoxValorPositivo")
        self.verticalLayout_2.addWidget(self.comboBoxValorPositivo)
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.groupBoxValorPositivo)
        self.btnAceptar = QtWidgets.QPushButton(self.frame)
        self.btnAceptar.setObjectName("btnAceptar")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.btnAceptar)
        self.labelCargando = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelCargando.setFont(font)
        self.labelCargando.setObjectName("labelCargando")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.labelCargando)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBoxAlgoritmo = QtWidgets.QComboBox(self.frame)
        self.comboBoxAlgoritmo.setObjectName("comboBoxAlgoritmo")
        self.comboBoxAlgoritmo.addItem("")
        self.comboBoxAlgoritmo.addItem("")
        self.comboBoxAlgoritmo.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.comboBoxAlgoritmo)
        self.horizontalLayout.addWidget(self.frame)
        self.frameTablas = QtWidgets.QFrame(Form)
        self.frameTablas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTablas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTablas.setObjectName("frameTablas")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameTablas)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frameTablas)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.labelAlgoritmo = QtWidgets.QLabel(self.frameTablas)
        self.labelAlgoritmo.setText("")
        self.labelAlgoritmo.setObjectName("labelAlgoritmo")
        self.verticalLayout.addWidget(self.labelAlgoritmo)
        self.tablaResultados = QtWidgets.QTableView(self.frameTablas)
        self.tablaResultados.setObjectName("tablaResultados")
        self.verticalLayout.addWidget(self.tablaResultados)
        self.horizontalLayout.addWidget(self.frameTablas)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "K Fold Cross Validation"))
        self.label.setText(_translate("Form", "Número de folds"))
        self.numFolds.setItemText(0, _translate("Form", "2"))
        self.numFolds.setItemText(1, _translate("Form", "3"))
        self.numFolds.setItemText(2, _translate("Form", "5"))
        self.numFolds.setItemText(3, _translate("Form", "10"))
        self.numFolds.setItemText(4, _translate("Form", "Leave one out"))
        self.groupBoxValorPositivo.setTitle(_translate("Form", "Valor positivo"))
        self.label_3.setText(_translate("Form", "Elige el valor positivo"))
        self.btnAceptar.setText(_translate("Form", "Aceptar"))
        self.labelCargando.setText(_translate("Form", "Calculando..."))
        self.label_4.setText(_translate("Form", "Algoritmo"))
        self.comboBoxAlgoritmo.setItemText(0, _translate("Form", "KNN"))
        self.comboBoxAlgoritmo.setItemText(1, _translate("Form", "Naive Bayes"))
        self.comboBoxAlgoritmo.setItemText(2, _translate("Form", "One R"))
        self.label_2.setText(_translate("Form", "Resultados de la evaluación"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
